### ISSUE TITLE
Add Navigation with Separate Pages for Each Feedback Section

### ISSUE THREAD

**Issue by nikhila-kuchimanchi** [acmpesuecc/oratory_coach_results#1]
Split the feedback sections (Facial Gestures, Body Gestures, Posture, etc.) into separate pages. Create a navigation menu or buttons on the results page for the user to navigate between these individual pages.

**Comment by Roshr2211** [comment]
Kindly assign me this. Im working on it.
![image](https://github.com/user-attachments/assets/7afbb776-eba4-498b-915a-d0c088471fdb)

**Comment by nikhila-kuchimanchi** [comment]
!assign @Roshr2211

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by asmitdesai** [comment]
can i get assigned to this

**Comment by Omkar-Patil-08-05** [comment]
can i get assigned to this

**Comment by Git-Cat-21** [comment]
can i be assigned to it
