### ISSUE TITLE
UI/UX Enhancement

### ISSUE THREAD

**Issue by nikhila-kuchimanchi** [acmpesuecc/oratory_coach_results#14]
Enhance the UI/UX design for this repo

**Comment by Salma-101** [comment]
could I?

**Comment by nikhila-kuchimanchi** [comment]
!assign @Salma-101

**Comment by mahika34** [comment]
can i be assigned?

**Comment by mahika34** [comment]
can i still be assigned?

**Comment by Git-Cat-21** [comment]
Can I be assigned

**Comment by Ruchavw** [comment]
can i be assigned

**Comment by sujith27pes** [comment]
Can i be assigned?

**Comment by sujith27pes** [comment]
i have been working on a similar ui/ux for a webpage for one of my personal project.So probably i can use my knowledge in that to quickly make the changes

**Comment by Roshr2211** [comment]
Can i be assigned. I am working on it.
![image](https://github.com/user-attachments/assets/e5eee783-3fe6-4391-9e83-0172c33cb6ff)

**Comment by Salma-101** [comment]
I've sent a pull request and made modifications to the ui
