### ISSUE TITLE
Implement User Authentication

### ISSUE THREAD

**Issue by nikhila-kuchimanchi** [acmpesuecc/oratory_coach_results#2]
Create a log-in page and add a user authentication system to the application to allow users to sign up, log in, and manage their profiles.

**Comment by sujith27pes** [comment]
Can u pls assign this to me @sujith27pes

**Comment by sujith27pes** [comment]
Can u pls assign this to me @sujith27pes

**Comment by nikhila-kuchimanchi** [comment]
!assign @sujith27pes

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @sujith27pes

**Comment by nikhila-kuchimanchi** [comment]
!deassign
