### ISSUE TITLE
Improve UI/UX

### ISSUE THREAD

**Issue by nikhila-kuchimanchi** [acmpesuecc/oratory_coach_results#3]
Improve UI/UX with CSS Animations, Hover Effects, subtle animations for buttons, etc. The source code can be converted to Javascript before implementation of CSS but this is not necessary

**Comment by asmitdesai** [comment]
can you assign this to me

**Comment by Salma-101** [comment]
can you assign me this?

**Comment by nikhila-kuchimanchi** [comment]
!assign @Salma-101

**Comment by sujith27pes** [comment]
can u pls assign this to me @sujith27pes

**Comment by nikhila-kuchimanchi** [comment]
@sujith27pes only one person can be assigned one issue at a time

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by Lalith2907** [comment]
assign me this pls

**Comment by Ayush-jk** [comment]
pls assign

**Comment by nikhila-kuchimanchi** [comment]
!assign @Lalith2907

**Comment by Lalith2907** [comment]
@nikhila-kuchimanchi how much time do i have??

**Comment by nikhila-kuchimanchi** [comment]
the timer is automatically set to 45 min, if you require more time I will assign it to you once this timer runs out

**Comment by Lalith2907** [comment]
ohh alrightt thank youu
will let you know if required

**Comment by Lalith2907** [comment]
@nikhila-kuchimanchi could i pls get a little more time??

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @Lalith2907 15

**Comment by Salma-101** [comment]
can you assign me

**Comment by nikhila-kuchimanchi** [comment]
@Salma-101 I'll assign it to you in 15 min so you can commit your code

**Comment by Salma-101** [comment]
can you assign me.. im done with it

**Comment by Git-Cat-21** [comment]
can i be assigned to it

**Comment by nikhila-kuchimanchi** [comment]
!assign @Salma-101

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @Salma-101

**Comment by Git-Cat-21** [comment]
can i be assigned to it

**Comment by mahika34** [comment]
can i be assigned?

**Comment by nikhila-kuchimanchi** [comment]
!deassign
