### ISSUE TITLE
Add User Input for Real-Time Feedback Customization

### ISSUE THREAD

**Issue by nikhila-kuchimanchi** [acmpesuecc/oratory_coach_results#4]
Add a new page and implement a feature that allows users to input their speech video or audio file. The application should then analyze the new data and provide real-time, customized feedback for facial gestures, body gestures, sentiment analysis, etc. Once the user inputs the data redirect them to the results page showing an aggregate result. User can then navigate to the various web pages to see their results in detail

Note: THE INPUT GIVEN DOES NOT NEED TO BE SAVED. The audio/visual input given by the user does not need to be saved or processed, Only implement the front-end aspects of this issue.

**Comment by Salma-101** [comment]
can you assign this to me?

**Comment by nikhila-kuchimanchi** [comment]
!assign @Salma-101

**Comment by Boffin-Omega** [comment]
can you assign this to me?

**Comment by Salma-101** [comment]
I'm going for dinner, will continue working on this again once back

**Comment by Salma-101** [comment]
Starting again now

**Comment by Salma-101** [comment]
could you reassign me? Almost done

**Comment by nikhila-kuchimanchi** [comment]
yeah sure

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @Salma-101

**Comment by Boffin-Omega** [comment]
Im done. can i submit a pr?

**Comment by Boffin-Omega** [comment]
Username: Boffin-Omega
Added an input page and an aggregate results page
I also linked stylesheet in every page instead of the original copy pasted css.
![{41063787-D3FF-4AE3-96AB-32B8F3130C5E}](https://github.com/user-attachments/assets/41d64ff0-20ca-4739-b232-04a2a584fab1)
![{D2A466DD-20E9-4695-8CB3-45AD354308B8}](https://github.com/user-attachments/assets/6262dc60-e273-4648-9ffa-fbee9528df4b)
![{C59AA06C-4F51-47A3-A528-9385CDE4E3DD}](https://github.com/user-attachments/assets/529c2031-d6dc-4d0c-ba9e-883173138f38)

added link to stylesheet in every page
![{6A82FB42-EEA3-41AB-BD1F-314C851C41D1}](https://github.com/user-attachments/assets/4c5473d0-3da1-4827-9307-2c66733a9292)

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @Boffin-Omega

**Comment by nikhila-kuchimanchi** [comment]
@Boffin-Omega you should be able to submit a pr now

**Comment by Boffin-Omega** [comment]
thank you

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @Boffin-Omega

**Comment by nikhila-kuchimanchi** [comment]
@Boffin-Omega did you fork your code?

**Comment by Git-Cat-21** [comment]
can i be assigned to it

**Comment by Boffin-Omega** [comment]
> @Boffin-Omega did you fork your code?

i did and i tried cleaning up the css in every page by moving it to one file, but now the styles dont apply to rest of the pages

**Comment by Boffin-Omega** [comment]
sry , id like to be deassigned

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @Git-Cat-21

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by Git-Cat-21** [comment]
@nikhila-kuchimanchi assign it back please still working on it almost done

**Comment by nikhila-kuchimanchi** [comment]
!assign @Git-Cat-21

**Comment by bwaklog** [comment]
@nikhila-kuchimanchi please decide to deassign the current assignee or extend the time for their issue

**Comment by nikhila-kuchimanchi** [comment]
!deassign
