### ISSUE TITLE
Add Progress Tracking and Visualization

### ISSUE THREAD

**Issue by nikhila-kuchimanchi** [acmpesuecc/oratory_coach_results#5]
Introduce a progress tracking feature where users can view their performance history over multiple speeches. Use graphs or charts to visualize improvements in areas such as eye contact, tone, and body gestures. Make sure only authenticated users have access to this page.

Note: ONLY IMPLEMENT FRONT-END ASPECTS OF THIS ISSUE

**Comment by Anirudh10070** [comment]
please assign this to me

**Comment by nikhila-kuchimanchi** [comment]
!assign @Anirudh10070

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @Anirudh10070

**Comment by Anirudh10070** [comment]
can u please elaborate this <Make sure only authenticated users have access to this page.>

**Comment by Anirudh10070** [comment]
Make sure only authenticated users have access to this page.

how do i do it

**Comment by nikhila-kuchimanchi** [comment]
@Anirudh10070 only users who have a log-in id and password can access the page

**Comment by Anirudh10070** [comment]
yeah i have just done it
as in the issue it was only asked to set up the front end part ..i made a basic login page to authenticate and a Performance tracker with bar graphs to visualize

**Comment by nikhila-kuchimanchi** [comment]
!deassign

**Comment by nikhila-kuchimanchi** [comment]
!assign @Anirudh10070

**Comment by nikhila-kuchimanchi** [comment]
@Anirudh10070 have you made the changes requested

**Comment by nikhila-kuchimanchi** [comment]
!deassign
